### ISSUE TITLE
关联列支持换行和点击跳转

### ISSUE THREAD

**Issue by 5kyfkr** [Misuzu2027/sywidget-block-database-view#1]
大佬您好，如图，希望能支持换行，现在要拖滚动条不方便查看，以及希望支持点击跳转关联列中的文档，不要求有编辑功能，只要能跳转过去就好啦
![image](https://github.com/Misuzu2027/sywidget-block-database-view/assets/63196026/ba2ea003-babb-47ea-9657-22ebab6df608)

**Comment by Misuzu2027** [comment]
集市已经更新 v0.0.4，优化了关联列的显示和跳转，麻烦看看体验如何。

**Comment by 5kyfkr** [comment]
> 集市已经更新 v0.0.4，优化了关联列的显示和跳转，麻烦看看体验如何。

赞，效果好极了
另外就是插件的字体能不能跟随思源设置的字体，感觉用微软雅黑太细了
或者说，如何需改挂件字体大佬知道嘛，挂件里的字体好像默认都是微软雅黑，然后css好像改不了

**Comment by Misuzu2027** [comment]
字体这方面确实不清楚，五一后有空研究一下。

**Comment by Misuzu2027** [comment]
写了一个 js 的代码片段，可以让挂件块使用思源编辑器设置的字体，代码如下：
```javascript
// 创建一个 MutationObserver 实例，用来监视 DOM 树的变化
let observer = new MutationObserver(async function (mutationsList) {
    // 遍历所有发生变化的 mutation
    mutationsList.forEach(function (mutation) {
        // 检查每个 mutation 中新增的节点
        mutation.addedNodes.forEach(function (node) {
            // 如果新增的节点是一个 iframe 元素
            if (node.tagName
                && node.tagName.toLowerCase() === 'div'
                && node.getAttribute('data-type') === 'NodeWidget'
                && node.getAttribute('data-subtype') === 'widget'
                && node.classList.contains('iframe')) {
                let widgetIframe = node.querySelector("iframe");
                if (widgetIframe) {
                    // 添加监听器到这个新的 iframe 元素
                    addListenerToIframe(widgetIframe);
                }
            }
        });
    });
});

// 配置 MutationObserver 监听的目标节点和要观察的变动类型
observer.observe(document.body, { childList: true, subtree: true });

// 定义一个函数，用来给 iframe 元素添加监听器
async function addListenerToIframe(iframe) {
    // 使用思源编辑器字体
    let editorFontFamily = window.siyuan.config.editor.fontFamily;
    // 可以手动指定字体
    // let editorFontFamily = "宋体";
    // 编辑器没有设置字体
    if (!editorFontFamily) {
        return;
    }
    // const startTime = performance.now();
    // 监听 iframe 的 load 事件
    iframe.addEventListener('load', function () {
        // iframe 内容加载完成后执行的操作
        // console.log('iframe load 内容加载完成');
        // const endTime = performance.now(); // 记录结束时间
        // const executionTime = endTime - startTime; // 计算时间差
        // console.log(`iframe load 消耗时间 : ${executionTime} ms`);
        // 获取 iframe 的内容文档
        let iframeDocument = iframe.contentDocument || iframe.contentWindow.document;
        // 创建一个 <style> 元素
        let style = iframeDocument.createElement('style');
        style.type = 'text/css';
        // 设置 CSS 样式，强制使用指定字体
        style.textContent = `body { font-family: ${editorFontFamily} }`;
        // 将样式添加到 iframe 的内容文档中
        iframeDocument.head.appendChild(style);
    });
}
```

**Comment by 5kyfkr** [comment]
> 写了一个 js 的代码片段，可以让挂件块使用思源编辑器设置的字体，代码如下：
> 
> ```js
> // 创建一个 MutationObserver 实例，用来监视 DOM 树的变化
> let observer = new MutationObserver(async function (mutationsList) {
>     // 遍历所有发生变化的 mutation
>     mutationsList.forEach(function (mutation) {
>         // 检查每个 mutation 中新增的节点
>         mutation.addedNodes.forEach(function (node) {
>             // 如果新增的节点是一个 iframe 元素
>             if (node.tagName
>                 && node.tagName.toLowerCase() === 'div'
>                 && node.getAttribute('data-type') === 'NodeWidget'
>                 && node.getAttribute('data-subtype') === 'widget'
>                 && node.classList.contains('iframe')) {
>                 let widgetIframe = node.querySelector("iframe");
>                 if (widgetIframe) {
>                     // 添加监听器到这个新的 iframe 元素
>                     addListenerToIframe(widgetIframe);
>                 }
>             }
>         });
>     });
> });
> 
> // 配置 MutationObserver 监听的目标节点和要观察的变动类型
> observer.observe(document.body, { childList: true, subtree: true });
> 
> // 定义一个函数，用来给 iframe 元素添加监听器
> async function addListenerToIframe(iframe) {
>     // 使用思源编辑器字体
>     let editorFontFamily = window.siyuan.config.editor.fontFamily;
>     // 可以手动指定字体
>     // let editorFontFamily = "宋体";
>     // 编辑器没有设置字体
>     if (!editorFontFamily) {
>         return;
>     }
>     // const startTime = performance.now();
>     // 监听 iframe 的 load 事件
>     iframe.addEventListener('load', function () {
>         // iframe 内容加载完成后执行的操作
>         // console.log('iframe load 内容加载完成');
>         // const endTime = performance.now(); // 记录结束时间
>         // const executionTime = endTime - startTime; // 计算时间差
>         // console.log(`iframe load 消耗时间 : ${executionTime} ms`);
>         // 获取 iframe 的内容文档
>         let iframeDocument = iframe.contentDocument || iframe.contentWindow.document;
>         // 创建一个 <style> 元素
>         let style = iframeDocument.createElement('style');
>         style.type = 'text/css';
>         // 设置 CSS 样式，强制使用指定字体
>         style.textContent = `body { font-family: ${editorFontFamily} }`;
>         // 将样式添加到 iframe 的内容文档中
>         iframeDocument.head.appendChild(style);
>     });
> }
> ```

厉害了大佬，非常有效

**Comment by 5kyfkr** [comment]
由于这个JS检测会影响数据库选项卡的点开速度
https://github.com/siyuan-note/siyuan/issues/11249#issuecomment-2095863278
我排除了对数据库NodeAttributeView类的监控，试了不会增加延时
```css
// 创建一个 MutationObserver 实例，用来监视 DOM 树的变化
let observer = new MutationObserver(async function (mutationsList) {
    // 遍历所有发生变化的 mutation
    mutationsList.forEach(function (mutation) {
        // 检查每个 mutation 中新增的节点
        mutation.addedNodes.forEach(function (node) {
            // 如果新增的节点是一个 iframe 元素
            if (node.tagName
                && node.tagName.toLowerCase() === 'div'
                && node.getAttribute('data-type') === 'NodeWidget'
                && node.getAttribute('data-subtype') === 'widget'
                && node.classList.contains('iframe')) {
                let widgetIframe = node.querySelector("iframe");
                if (widgetIframe) {
                    // 添加监听器到这个新的 iframe 元素
                    addListenerToIframe(widgetIframe);
                }
            } else if (node.tagName
                && node.tagName.toLowerCase() === 'div'
                && node.getAttribute('data-type') === 'NodeAttributeView') {
                // 如果新增的节点是 NodeAttributeView 类型，则跳过处理
                return;
            }
        });
    });
});

// 配置 MutationObserver 监听的目标节点和要观察的变动类型
observer.observe(document.body, { childList: true, subtree: true });

// 定义一个函数，用来给 iframe 元素添加监听器
async function addListenerToIframe(iframe) {
    // 使用思源编辑器字体
    //let editorFontFamily = window.siyuan.config.editor.fontFamily;
    // 可以手动指定字体
     let editorFontFamily = "HarmonyOS Sans SC Medium";
    // 编辑器没有设置字体
    if (!editorFontFamily) {
        return;
    }
    // const startTime = performance.now();
    // 监听 iframe 的 load 事件
    iframe.addEventListener('load', function () {
        // iframe 内容加载完成后执行的操作
        // console.log('iframe load 内容加载完成');
        // const endTime = performance.now(); // 记录结束时间
        // const executionTime = endTime - startTime; // 计算时间差
        // console.log(`iframe load 消耗时间 : ${executionTime} ms`);
        // 获取 iframe 的内容文档
        let iframeDocument = iframe.contentDocument || iframe.contentWindow.document;
        // 创建一个 <style> 元素
        let style = iframeDocument.createElement('style');
        style.type = 'text/css';
        // 设置 CSS 样式，强制使用指定字体
        style.textContent = `body { font-family: ${editorFontFamily} }`;
        // 将样式添加到 iframe 的内容文档中
        iframeDocument.head.appendChild(style);
    });
}

```
