### ISSUE TITLE
默认读取上方块id

### ISSUE THREAD

**Issue by HibernalGlow** [Misuzu2027/sywidget-block-database-view#2]
挂件很有用，但是我一般是把块添加到数据库的，所以默认文档id非常不方便。可以考虑文档第一行绑定文档，上方有块就绑定块？

**Comment by HibernalGlow** [comment]
可以参考这个https://github.com/OpaqueGlass/progressBarT-sywidget

**Comment by Misuzu2027** [comment]
可以实现，不过这个逻辑作为默认可能不太通用。
你看这样子合适吗，在全局设置中添加一个默认读取目标块的方式，分别有：文档块、挂件上方块、挂件下方块。
这样以后创建新挂件时就能读取到自己习惯的方式。

**Comment by HibernalGlow** [comment]
可以可以

**Comment by Misuzu2027** [comment]
集市已经更新 v0.0.4，增加了该设置，麻烦试试体验如何。

**Comment by HibernalGlow** [comment]
完美，感谢
