### ISSUE TITLE
插件版？

### ISSUE THREAD

**Issue by HibernalGlow** [Misuzu2027/sywidget-block-database-view#3]
我把数据库当标签用的，所以希望能有全局默认展示数据库属性的功能。本来是在等这位作者的[https://github.com/InEase/SiYuan-Attributes-Panel/issues/7]，不过他好像很忙

**Comment by Misuzu2027** [comment]
不太清楚需要实现什么功能，大约的理解是想要在有 **数据库属性的块** 下方自动创建创建该挂件吗？

**Comment by HibernalGlow** [comment]
是的，进阶的话就是自定义可显示的数据库

**Comment by Misuzu2027** [comment]
自动插入功能挂件确实不好做到了，不过我觉得挂件的插入也不是特别麻烦的事情，在给这个块添加到数据库的时候顺手在下方插入一个挂件就可以了。
目前一个快有多个数据库的时候，会记录最后查看的数据库，下次打开文档会默认展示最后查看的数据库。

**Comment by HibernalGlow** [comment]
那有办法用quicker或是快捷键触发吗

**Comment by Misuzu2027** [comment]
我不太会 quicker，如果 quicker 可以访问思源接口，是可以做到的。流程大致如下：

1. 获取所有含有 数据库属性的块。
2. 获取所有 视图挂件块的属性。
3. 过滤已经存在 视图挂件 的 数据库属性块。
4  给没有 视图挂件 的 数据库属性块 ，调用接口在下方添加 视图挂件，同时给 新添加的视图挂件 添加属性，让它指向数据库属性块。

**Comment by HibernalGlow** [comment]
感谢
