### ISSUE TITLE
关于属性值修改的支持

### ISSUE THREAD

**Issue by QMike0** [Misuzu2027/sywidget-block-database-view#4]
佬，为啥明确不会支持内容块数据库属性值的修改，感觉这是很重要的一个功能点呀：（

**Comment by Misuzu2027** [comment]
主要原因是实力不够，单纯的文本框数字框修改还好，像多选、资源、关联、汇总等类型就无法完成了；索性就干脆不支持修改了。同时我个人来说，修改操作不太频繁，点击块的**数据库角标**再进行修改也更有安全感。

**Comment by QMike0** [comment]
嗯嗯，不过还是觉得支持属性值修改才是完整的数据库体验，不用额外操作，个人也比较讨厌点击角标后的弹窗😂

话说回来，无论是从实现难度还是交互体验来说，这个功能还是得官方实现比较好，可惜D大明确说交给社区emmm

最后谢谢佬的贡献，终于不用纠结是否在文首手动加上属性值了

**Comment by Misuzu2027** [comment]
我也是希望官方能够实现，但是看到D大的态度，只能自己应付一下了😩
